# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: mikityuk
  tag: "1.0.6-3b05ce8"
  arch: amd64
secret:
  name: "kbot"
  tokenKey: "token"
  tokenName: "TELE_TOKEN"
